# Generated by Django 2.1.2 on 2018-12-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video_con_pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=120)),
                ('date_conference', models.DateTimeField(auto_now_add=True)),
                ('conference_link', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='video_request',
            fields=[
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('requester', models.CharField(max_length=120)),
            ],
        ),
    ]
