# Generated by Django 2.1.2 on 2018-12-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Advertiser', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(default='AdvertisementImages/None/no-img.jpg', upload_to='AdvertisementsImages/')),
                ('link', models.URLField()),
            ],
        ),
    ]
