# Generated by Django 2.1.3 on 2018-12-19 07:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181219_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='user_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='home.user_profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_review',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 19, 12, 57, 20, 919182)),
        ),
    ]
