# Generated by Django 2.1.3 on 2018-12-19 08:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181219_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='labappointment',
            name='email_id',
        ),
        migrations.AlterField(
            model_name='labappointment',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.user_profile'),
        ),
        migrations.AlterField(
            model_name='user_review',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 19, 13, 45, 17, 71756)),
        ),
    ]
