# Generated by Django 2.1.3 on 2018-12-19 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_review',
            name='review_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 19, 12, 27, 3, 149485)),
        ),
    ]
